### PR TITLE
Improved code structure

### PR DESCRIPTION
**Pull request by prajwalpatil25**
# Description
The PR performs code restructuring to align with powerflex and powermax terraform provider code design. The PR does not change any logic/behaviour of the working code. 

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [X] I have verified that new and existing unit tests pass locally with my changes
- [X] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [X] Acceptance tests

### CODE REVIEW

**Review by shenda1 — COMMENTED** [review]
why the license file is removed? Also, GitHub action is failing.

**Review by shenda1 — COMMENTED** [review]
Also, why branch is created from dev instead of main?

**Comment by AnikaAgiwal2711** [comment]
Can we have some description so that it is easy to understand that what is being achieved in this PR.

**Comment by prajwalpatil25** [comment]
> Also, why branch is created from dev instead of main?

@shenda1 changed base branch to "main"

**Comment by prajwalpatil25** [comment]
> Can we have some description so that it is easy to understand that what is being achieved in this PR.

@AnikaAgiwal2711 Added description in PR summary

**Comment by prajwalpatil25** [comment]
> why the license file is removed? Also, GitHub action is failing.

@shenda1 Formatting errors are now resolved. [LICENCE](https://github.com/dell/terraform-provider-powerstore/blob/provider-sync/LICENSE) is there in the code I have removed duplicate LICENSE.txt

**Review by shenda1 — APPROVED** [review]

**Review by AnikaAgiwal2711 — APPROVED** [review]

**Pull request merged**
